services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        build: .docker/php
        container_name: example_app
        restart: unless-stopped
        ports:
            - 5173:5173
        environment:
            TZ: 'America/Sao_Paulo'
        volumes:
            - ./:/var/www:cached
        networks:
            - private_network
            
    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        build: .docker/nginx
        container_name: example_web
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        environment:
            TZ: 'America/Sao_Paulo'
        volumes:
            - ./:/var/www
        depends_on:
            - php
        networks:
            - private_network

    ####################################################################################################
    # phpMyAdmin for MariaDB
    # ####################################################################################################
    # mariadbAdmin:
    #     build: ./.docker/mariadbAdmin
    #     container_name: example_mariadbAdmin
    #     restart: unless-stopped
    #     ports:
    #         - "8080:80"
    #         - "4443:443"
    #     environment:
    #         PMA_HOST: mariadb
    #         PMA_PORT: 33306
    #         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-userpass}   
    #         TZ: 'America/Sao_Paulo'
    #         APP_HOST: ${APP_HOST}          
    #     #volumes:
    #     # - ./developer/mariadbAdmin/sessions:/sessions
    #     depends_on:
    #         - mariadb
    #     networks:
    #         - private_network

    #####################################################################################################
    # DATABASE (MariaDB)
    #####################################################################################################
    mariadb:
        image: mariadb
        container_name: example_mariadb
        restart: unless-stopped
        ports:
            - 33306:33306
        volumes:
            - ./.docker/mariadb/untracked/data:/var/lib/mysql
            - ./.docker/mariadb/untracked/logs:/var/log/mysql
            - ./.docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./.docker/mariadb/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-cursobdii}
            MYSQL_USER: ${DB_USERNAME:-username}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-userpass}
        networks:
            - private_network

    ####################################################################################################
    # phpMyAdmin for MySQL
    ####################################################################################################
    mysql_admin:
        build: ./.docker/mysql_admin
        container_name: example_mysql_admin
        restart: unless-stopped
        ports:
            - "8080:80"
            - "4443:443"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-userpass}   
            TZ: 'America/Sao_Paulo'
            APP_HOST: ${APP_HOST}          
        #volumes:
        # - ./developer/mysql_admin/sessions:/sessions
        depends_on:
            - mysql
        networks:
            - private_network
    ####################################################################################################
    # DATABASE (MySQL) - Intentionally Older Version
    ####################################################################################################
    mysql:
        image: mysql:8.1
        container_name: example_mysql
        restart: unless-stopped
        ports:
            - 3306:3306
        volumes:
            - ./.docker/mysql/untracked/data:/var/lib/mysql
            - ./.docker/mysql/untracked/logs:/var/log/mysql
            - ./.docker/mysql/untracked/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./.docker/mariadb/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-cursobdii}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
            TZ: 'America/Sao_Paulo'
        networks:
            - private_network

    ###################################################################################################
    # PostgreSQL
    ###################################################################################################
    # pgsql:
    #     image: postgres:16
    #     container_name: example_pgsql
    #     restart: unless-stopped
    #     ports:
    #         - 5432:5432
    #     volumes:
    #         - ./.docker/pgsql/data:/var/lib/postgresql/data
    #         - ./.docker/pgsql/sql:/docker-entrypoint-initdb.d
    #     environment:
    #         - POSTGRES_USER=${DB3_USERNAME:-username}
    #         - POSTGRES_PASSWORD=${DB3_PASSWORD:-root}
    #         - POSTGRES_DB=${DB3_DATABASE:-laravel}
    #     networks:
    #         - private_network

    ####################################################################################################
    # pgAdmin
    ####################################################################################################
    # pgadmin:
    #     image: dpage/pgadmin4
    #     container_name: example_pgadmin
    #     restart: unless-stopped
    #     ports:
    #         - 5050:80
    #     environment:
    #         - PGADMIN_DEFAULT_EMAIL=${DB3_USERNAME:-username@gmail.com}
    #         - PGADMIN_DEFAULT_PASSWORD=${DB3_PASSWORD:-root}
    #     depends_on:
    #         - pgsql
    #     networks:
    #         - private_network
     ####################################################################################################
    # SQL Server
    ####################################################################################################  
    # sqlsrv:
    #     build: ./developer/sqlsrv
    #     restart: unless-stopped
    #     container_name: example_sqlsrv_dev
    #     environment:
    #         ACCEPT_EULA: 'Y'
    #         MSSQL_SA_PASSWORD: ${DB4_PASSWORD:-<YourStrong@Passw0rd>}
    #         MSSQL_TCP_PORT: ${DB4_PORT:-1433} 
    #         MSSQL_DATA_DIR: /var/opt/mssql/data
    #         MSSQL_PID: 'Developer' 
    #         #MSSQL_PID: "Express"
    #         MSSQL_LC_COLLATION: "Latin1_General_CI_AS"
    #         MSSQL_LANG: "pt_br"
    #     ports: 
    #         - "1433:1433"
    #     volumes:
    #         - ./developer/sqlsrv/data/data:/var/opt/mssql/data
    #         - ./developer/sqlsrv/data/log:/var/opt/mssql/log
    #         - ./developer/sqlsrv/data/secrets:/var/opt/mssql/secrets 
    #     networks:
    #         - private_network
            
    ####################################################################################################
    # Docker Workspace Network
    #################################################################################################### 
networks:
    private_network:
        driver: bridge